services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      TRANSACTION_SERVICE_URL: http://transaction-management:3000
      USER_SERVICE_URL: http://localhost:5002
      ANALYTICS_SERVICE_URL: http://localhost:5003
      PORT: 4000
    networks:
      - shared_network

networks:
  shared_network:
    external: true      